//**************************************************************************
// * file:        Mac80211Pkt.msg
// *
 
// * copyright:   (c) by 'the Glimmer Twins'
// *              Telecommunication Networks Group
// *              TU-Berlin
// * email:       loebbers@tkn.tu-berlin.de
// **************************************************************************
// * part of:     framework implementation developed by tkn
// *************************************************************************/

cplusplus {{
#include "MacPkt_m.h"
}}

class MacPkt;
namespace Veins;

// Defines all fields of an 802.11 MAC frame
packet Mac80211Pkt extends MacPkt
{

}
